# Generated by Django 4.2.13 on 2024-06-08 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Mobile No!', regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, default='', max_length=150, null=True)),
                ('gender', models.SmallIntegerField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userdetails',
                'ordering': ('-created_date',),
            },
        ),
    ]
