# Generated by Django 4.2.13 on 2024-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='fullname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10),
        ),
    ]
